name: Docker Build
on:
  push:
    branches:
      - master
    paths:
      - "image/**"
jobs:
  publish:
    name: Push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get release version
        id: get_version
        run: echo ::set-env name=VERNEMQ_VERSION::$(cat image/version.txt)
      - name: Push
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          workdir: image
          buildargs: VERNEMQ_VERSION
          name: jeffgrunewald/vernemq
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ env.VERNEMQ_VERSION }}"
